apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
spec:
  template:
    spec:
      containers:
        - image: ha_elixir
          name: ha-elixir
          command: ["/app/bin/migrate"]
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: ecto://postgres:postgres@ha-elixir-postgres-postgresql.default.svc.cluster.local/ha_elixir_prod
            - name: SECRET_KEY_BASE
              value: Qlb4iWX094tBaUmfD31eA8O+cqHpp5CnH+sFQrjqFJZ9GdIJa4XG/4OW2YZy1Asc


      restartPolicy: Never
